version: "3.4"

services:
  producer-async:
    image: producer-async
    build:
      context: .
      dockerfile: Producer.Async/Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  kafka:
    image: iskorotkov/kafka-dependent
    ports:
      - 9092

  zookeeper:
    image: zookeeper
    expose:
      - 2181
